---
# install
- name: Ensure snmpd is installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ snmp_packages }}"

# configure
- name: Place snmpd configuration file in place.
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 00644
  notify: restart snmpd

# service
- name: Ensure snmpd is started and enabled to start at boot.
  service: name=snmpd state=started enabled=yes
